baseURL = 'https://ebefrank.github.io/'
theme = "PaperMod"
languageCode = 'en-us'

[[languages.en.menu.main]]
	name = "German"
	url = "/de/"
	weight = 10

[[languages.de.menu.main]]
	name = "English"
	url = "/en/"
	weight = 10

title = 'Sichten und Schl√ºsse'

[params] 
	author = "Eberhard Frank"
